**UNIVERSIDADE FEDERAL DO PARÁ**

Faculdade de Computação

Professor: Elinei Santos

Aluno: Luiz Sérgio Samico Maciel Filho

**Primeira Lista Avaliativa**

---

#### 1ª Questão: 

Uma partícula com carga +2 nC (1 nanocoulomb é $1\times10^{-9}$) está localizada na origem. Qual é o campo elétrico devido a essa partícula na posição: (-0,2; -0,2; -0,2) m?

##### **Solução**

O campo elétrico, $\vec{E}$, em um determinado ponto no espaço é dado pela equação $$\vec{F}=q\vec{E} \tag{1},$$ onde $q$ é a carga da partícula na origem.

Se o campo varia de um ponto ao outro, ele pode ser escrito matemáticamente como um vetor em função da posição, escrito na forma:
$$ \vec{E}(x,y,z) = E_x(x,y,z)\hat{x} + E_y(x,y,z)\hat{y} + E_z(x,y,z)\hat{z}, \tag{2}$$

onde $E_x$, $E_y$ e $E_z$ são as componentes de $\vec{E}$, e $x$, $y$ e $z$ são as cordenadas cartesianas do ponto em relação a um sistema de coordenadas. É comum que $ \vec{E}(x,y,z) $ seja representado como $ \vec{E}(\vec{r})$, onde $\vec{r}$ é o vetor do ponto de origem até o ponto onde o campo deve ser determinado.

De modo que, considerando a equação da Lei de Coulomb ao longo do vetor unitário $\hat{r}$ $$ \vec{F}=k_e\frac{q_1 q_2}{r^2}\hat{r}, \tag{3}$$ onde a partícula de carga $q_2$ está na origem e a partícula de carga $q_1$ está no fim do vetor posição $\vec{r}$, e combinando com a Equação (1), temos $$ \vec{E}(\vec{r})=k_e \frac{q_2}{r^2}\hat{r}. \tag{4}$$

Reescrevendo, temos $$ \vec{E}=k_e \frac{Q}{R^2}\hat{R}= \frac{Q}{R^2}\frac{\vec{R}}{R}. \tag{5} $$

Assim, considerando a magnitude $R$ composta pelos componentes de $\vec{R}$ ($R_x$, $R_y$ e $R_z$), onde $$ \vec{R} = \vec{r} - \vec{r}_Q, \tag{6}$$ em que $r_Q$ é a posição da carga pontual e $\vec{r}$ é a posição onde desejamos calcular o campo elétrico, temos que $$ R = [(x-x_q)^2 + (y-y_q)^2 + (z-z_q)^2]^{\frac{1}{2}}. \tag{7}$$

E, portanto, podemos reescrever a Equação (5) como $$ \vec{E}=k_e \left( \frac{Q}{R^2}\right)\hat{E}, \tag{8} $$ onde $$ \hat{E}=\left( \frac{x-x_Q}{R}\right)\hat{x} + \left( \frac{y-y_Q}{R}\right)\hat{y} + \left( \frac{z-z_Q}{R}\right)\hat{z}, \tag{9}$$ com $R$ definido na Equação (7).

##### Equação para obter o vetor campo elétrico

Finalmente, podemos escrever a equação para obter o vetor campo elétrico em determinada coordenada $(x, y, z)$ decorrente de uma partícula nas coordenadas $(xq, yq, zq)$: $$ \vec{E}=k_e\frac{Q}{R^2}\left[ \frac{x-x_Q}{[(x-x_q)^2 + (y-y_q)^2 + (z-z_q)^2]^{\frac{1}{2}}}\hat{x} + \frac{y-y_Q}{[(x-x_q)^2 + (y-y_q)^2 + (z-z_q)^2]^{\frac{1}{2}}}\hat{y} + \frac{z-z_Q}{[(x-x_q)^2 + (y-y_q)^2 + (z-z_q)^2]^{\frac{1}{2}}}\hat{z}\right]. \tag{10} $$

##### Equação para obter o módulo do vetor campo elétrico

Lembrando que a equação para obter o módulo do vetor campo elétrico é $$ E = \sqrt{Ex^2+Ey^2+Ez^2} \tag{11}$$

O código em Python que determina o campo elétrico na posição (-0,2; -0,2; -0,2) devido a uma partícula, na origem, de carga $2\mu C$ é descrito a seguir.


In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [67]:
# Função para encontrar o vetor campo elétrico (Equação (11))
def Ev(q, rq, r):
    k = 9e9
    x, y, z = r
    xq, yq, zq = rq
    R = ((x-xq)**2 + (y-yq)**2 + (z-zq)**2)**0.5
    ex = (k*(q/(R**2)))*(x-xq)/(R)
    ey = (k*(q/(R**2)))*(y-yq)/(R)
    ez = (k*(q/(R**2)))*(z-zq)/(R)
    E = np.sqrt(ex**2 + ey**2 + ez**2)
    return ex, ey, ez, E

r1 = (-0.2, -0.2, -0.2)
rq1 = (0, 0, 0)
q1 = 1e-6

Ex1, Ey1, Ez1, E1 = Ev(q1, rq1, r1)

print(f'O vetor campo elétrico resultante no ponto {r} é:\n\
    Ev = {Ex1:.1E}x\u0302 + {Ey1:.1E}y\u0302 + {Ez1:.1E}z\u0302')
print(f'\nO módulo do vetor campo elétrico resultante no ponto {r} é:\n\
    E = {E1:.1E}.')


O vetor campo elétrico resultante no ponto (-0.2, -0.2, -0.2) é:
    Ev = -4.3E+04x̂ + -4.3E+04ŷ + -4.3E+04ẑ

O módulo do vetor campo elétrico resultante no ponto (-0.2, -0.2, -0.2) é:
    E = 7.5E+04.


##### **Resposta**
De acordo com o resultado do programa, podemos escrever que o vetor campo elétrico resultante no ponto é: 
$$ \vec{E}=-4,3\times 10^4\hat{x} + -4,3\times 10^4\hat{y} + -4,3\times 10^4\hat{z} \text{ }N/C,$$
e que o módulo do vetor campo elétrico no ponto é $$ E=7,5 \times 10^4 N/C$$

---

#### 2ª Questão:
Descobriu-se que o campo elétrico na posição: $(-0,13; 0,14; 0)$ m é $\vec{E}=6,48 \times 10^3 \hat{i} + 8,64 \times 10^3 \hat{j} \text{ } N/C$. A única partícula carregada no encontro tem carga -3nc. Qual a posição desta partícula (vetor que localiza a partícula).

##### **Solução**
A intensidade do campo elétrico em um ponto é dado pela equação $$ E = k \frac{Q}{r^2} \tag{12}.$$ Dado que a questão fornece os valores para $Ex$ e $Ey$, podemos calcular $E$ por meio da Equação (11). Substituindo os valores de $Q$ fornecidos pela questão, e da constante eletrostática no vácuo $k=9 \times 10^9$, podemos descobrir $r$.

Sabemos também que o cosseno e o seno do ângulo $\theta$ entre o vetor campo elétrico e a horizontal do plano podem ser escritos como $$\cos{\theta}=\frac{x-x_q}{r} \text{  e  } \sin{\theta}=\frac{y-y_q}{r}, \tag{13}$$ e que, assumindo  trigonometricamente que a hipotenusa é o vetor campo elétrico $\vec{E}$, e o cateto adjacente é o vetor unitário $E_x \hat{x}$ do campo elétrico, o ângulo $\theta$ pode ser calculado através da equação: $$\theta = arccos(\frac{E_x \hat{x}}{\vec{E}}) \tag{14}.$$

Por fim, de posse de todas as variáveis necessárias para isolar $x_q$ e $y_q$, podemos descobrir seus valores. O código em Python que realiza esse cálculo é descrito a seguir.

In [47]:
# Função para aplicação da Equação (12)
def cElet(E=None, *, Q, r):
    """ Recebe n-1 parâmetros, onde os parâmetros são:
    E = um número para a intensidade do campo elétrico em Newtons/Coulomb
    Q = um número para a intensidade de carga elétrica geradora em Coulombs
    r = distância onde se irá medir o valor do campo elétrico em metros
    
    Retorna uma tupla (Q, r, E, F) onde:
    Q = Intensidade da carga elétrica geradora em Coulombs
    r = Distância em metros
    E = Intensidade do Campo elétrico em Newtons/Coulomb
    F = Força elétrica em Newtons
    """
    k = 9e9
    if E == None:
        return Q, r, (k*abs(Q))/(r**2), (k*abs(Q))/(r**2) * Q
    elif r == None:
        return Q, ((k*abs(Q))/(E))**0.5, E, E * Q
    else:
        return (E*(r**2))/(k), r, E, E * Q

# Variáveis fornecidas pela questão
Ex2 = 6.48e3
Ey2 = 8.64e3
rv2 = (-0.13, 0.14, 0)
x2, y2, z2 = rv2
q2 = -3e-9

# Descobrindo E a partir de seus vetores componentes (Equação (11))
E2 = np.sqrt(Ex2**2 + Ey2**2)
print(f'E = {E2}')

# Descobrindo r
r2 = cElet(E=E2, Q=q2, r=None)[1]
print(f'r = {r2}')

# Descobrindo theta, seno de theta e cosseno de theta
theta2 = np.arccos(Ex2/E2)
sentheta2, costheta2 = (np.sin(theta2), np.cos(theta2))
print(f'theta = {theta2}\nseno theta = {sentheta2}\ncosseno theta = {costheta2}')

# Trabalhando a equação (13) nós temos que:
## Descobrindo xq
xq2 = (costheta2*r2)+x2
print(f'xq = {xq2}')

## Descobrindo yq
yq2 = (sentheta2*r2)+y2
print(f'yq = {yq2}')

# Coordenadas da partícula (considerando que z=0)
rqv2 = (xq2, yq2, 0)
xq2, yq2, zq2 = rqv2

# Conferindo o resultado por meio da função Ev()
Ex2r, Ey2r, _, Er = Ev(q2, rqv2, rv2)
comparacao = ('iguais', 'corretos') if (round(Ex2r,2), round(Ey2r,2)) == (round(Ex2,2), round(Ey2, 2)) else ('diferentes', 'errados')
print(f'\nNas coordenadas calculadas para xq e yq {rqv2}:\n\
    Ex = {Ex2r:.2E}\n\
    Ey = {Ey2r:.2E},\n\
De modo que {Ex2r:.2E}x\u0302 + {Ey2r:.2E}y\u0302 é o vetor campo elétrico na coordenada {rv2}.')
print(f'\nComo os valores calculados -> ({Ex2r:.2E} e {Ey2r:.2E}) <- e os valores fornecidos pela questão\
 -> ({Ex2:.2E} e {Ey2:.2E}) <- são {comparacao[0]}, os cálculos estão {comparacao[1]}.')


E = 10800.0
r = 0.05
theta = 0.9272952180016123
seno theta = 0.8
cosseno theta = 0.6
xq = -0.1
yq = 0.18000000000000002

Nas coordenadas calculadas para xq e yq (-0.1, 0.18000000000000002, 0):
    Ex = 6.48E+03
    Ey = 8.64E+03,
De modo que 6.48E+03x̂ + 8.64E+03ŷ é o vetor campo elétrico na coordenada (-0.13, 0.14, 0).

Como os valores calculados -> (6.48E+03 e 8.64E+03) <- e os valores fornecidos pela questão -> (6.48E+03 e 8.64E+03) <- são iguais, os cálculos estão corretos.


##### **Resposta**
De acordo com o resultado do programa, as coordenadas da partícula são $(-0,1; 0,18)m$.

---

#### 3ª Questão
Um pequeno objeto com carga $q_1 = 6nC$ está localizado na origem. Um segundo pequeno objeto com carga $q_2=-5nC$ está localizado em $(0,05; 0,08;0)m$.

_a)_ Qual o campo elétrico resultante na posição $A$, em $(-0,04; 0,08; 0)m$, devido a $q_1$ e $q_2$?

_b)_ Se um pequeno objeto com carga $q_3=-3nC$ fosse colocado na posição $A$, qual seria a força sobre o objeto?

##### **Solução**
_a)_ O campo elétrico resultante em um ponto devido a ação de mais de uma carga constitui-se da soma vetorial do vetor campo elétrico de cada uma das cargas independentemente:
$$\vec{E}_{Total}=\sum_{i=1}^n\vec{E}_i, \tag{15}$$
lembrando que o vetor campo elétrico de cada uma das cargas pode ser obtido através da Equação (10) e o módulo do vetor campo elétrico através da Equação (11).

_b)_ Após resolver _a)_, obtemos $\vec{E}$, que podemos utilizar para resolver _b)_ por meio da Equação (1).

O código em python que realiza esses cálculos é descrito a seguir.

In [77]:
# Obtendo os vetores campo elétrico das cargas q1 e q2
q31 = 6e-9
rqv31 = (0, 0, 0)

q32 = -5e-9
rqv32 = (0.05, 0.08, 0)

rv3 = (-0.04, 0.08, 0)

## Usando a função Ev() para obter os vetores campo elétrico
Ex31, Ey31, Ez31, E31 = Ev(q31, rqv31, rv3)
Ex32, Ey32, Ez32, E32 = Ev(q32, rqv32, rv3)
Ex3 = sum((Ex31, Ex32))
Ey3 = sum((Ey31, Ey32))
E3 = np.sqrt(sum((Ex3**2, Ey3**2)))

# Obtendo o vetor campo elétrico total
Ev3 = (Ex3, Ey3)
print(f'O vetor campo elétrico resultante no ponto A é:\n\
    Ev = {Ev3[0]:.2E}x\u0302 + {Ev3[1]:.2E}y\u0302')

# Obtendo o módulo do vetor campo elétrico total
print(f'O módulo do vetor campo elétrico resultante no ponto A é:\n\
    E = {E3:.2E}')

# Obtendo a força exercida sobre q3=-3e-9
q33 = -3e-9
f3v = (q33*Ev3[0], q33*Ev3[1])
f3 = np.sqrt(sum((f3v[0]**2, f3v[1]**2)))

print(f'O vetor força elétrica resultante na partícula é:\n\
    Fev = {f3v[0]:.2E}x\u0302 + {f3v[1]:.2E}y\u0302')

print(f'O módulo do vetor força elétrica resultante na partícula é:\n\
    Fe = {f3:.2E}')

O vetor campo elétrico resultante no ponto A é:
    Ev = 2.54E+03x̂ + 6.04E+03ŷ
O módulo do vetor campo elétrico resultante no ponto A é:
    E = 6.55E+03
O vetor força elétrica resultante na partícula é:
    Fev = -7.61E-06x̂ + -1.81E-05ŷ
O módulo do vetor força elétrica resultante na partícula é:
    Fe = 1.96E-05


##### **Resposta**
_a)_ O campo elétrico resultante na posição $A$ devido a $q_1$ e $q_2$ é:
$$\vec{E} = 2,54 \times 10^3 \hat{x} + 6,04 \times 10^3 \hat{y}$$

_b)_ A força sobre o objeto seria:
$$\vec{F} = -7,61 \times 10^{-6} \hat{x} + -1,81 \times 10^{-5} \hat{y}$$

#### 4ª Questão

In [11]:
# Criando um array com as coordenadas de cada um dos vertices do cubo
cube = np.array(np.meshgrid([2e-3, 0], [2e-3, 0], [2e-3, 0])).T.reshape(-1,3)
print(cube)

[[0.002 0.002 0.002]
 [0.002 0.    0.002]
 [0.    0.002 0.002]
 [0.    0.    0.002]
 [0.002 0.002 0.   ]
 [0.002 0.    0.   ]
 [0.    0.002 0.   ]
 [0.    0.    0.   ]]


In [12]:
# Usando o princípio da superposição para calcular o campo elétrico resultante no ponto A
Extot = 0
Eytot = 0
Eztot = 0
q = 2e-9

for v in cube[1:]:
    Ex, Ey, Ez = Ev(v, cube[0], q)
    cost=np.arccos(Exx/Et)
    Extot += Ex
    Eytot += Ey
    Eztot += Ez
    Et=(Extot**2+Eytot**2+Eztot**2)**0.5
Etot = (Extot**2+Eytot**2+Eztot**2)**0.5

print(f'O vetor campo elétrico resultante no ponto A = {Extot: .1E}i + {Eytot: .1E}j + {Eztot: .1E}k')
print(f'O módulo do vetor campo elétrico resultante ={Etot: .1E}.')

TypeError: cannot unpack non-iterable float object