# Universidade Federal do Pará
## Faculdade de Computação
## Professor: Elinei Santos
## Aluno: Luiz Sérgio Samico Maciel Filho
## **Primeira Lista Avaliativa**

In [107]:
import numpy as np
import matplotlib.pyplot as plt

In [106]:
# Cálculo do vetor campo elétrico de uma carga pontual
def Ev(coordPtCampo, coordCargaPt, q):
    K=9e9
    x, y, z = coordPtCampo
    xq, yq, zq = coordCargaPt
    ex=(K*q)*(x-xq)/((x-xq)**2.+(y-yq)**2.+(z-zq)**2)**1.5
    ey=(K*q)*(y-yq)/((x-xq)**2.+(y-yq)**2.+(z-zq)**2)**1.5
    ez=(K*q)*(z-zq)/((x-xq)**2.+(y-yq)**2.+(z-zq)**2)**1.5
    return ex, ey, ez

coord1 = (0, 0.04, 0)
coord2 = (-0.03, 0, 0)

Ex, Ey, Ez = Ev(coord1, coord2, 1.e-6)

Et=(Ex**2+Ey**2+Ez**2)**0.5
cost=np.arccos(Ex/Et)

print(f'Ex = {Ex: .1E}\n')
print(f'Ey = {Ey: .1E}\n')
print(f'Módulo do campo elétrico = {Et: .1E} N/C\n')
print(f'O cosseno entre o campo e o eixo x = {cost:.2f}º')

Ex =  2.2E+06

Ey =  2.9E+06

Módulo do campo elétrico =  3.6E+06 N/C

O cosseno entre o campo e o eixo x = 0.93º


In [103]:
# Criando um array com as coordenadas de cada um dos vertices do cubo
cube = np.array(np.meshgrid([2e-3, 0], [2e-3, 0], [2e-3, 0])).T.reshape(-1,3)
print(cube)

[[0.002 0.002 0.002]
 [0.002 0.    0.002]
 [0.    0.002 0.002]
 [0.    0.    0.002]
 [0.002 0.002 0.   ]
 [0.002 0.    0.   ]
 [0.    0.002 0.   ]
 [0.    0.    0.   ]]


In [105]:
# Usando o princípio da superposição para calcular o campo elétrico resultante no ponto A
Extot = 0
Eytot = 0
Eztot = 0
q = 2e-9

for v in cube[1:]:
    Ex, Ey, Ez = Ev(v, cube[0], q)
    cost=np.arccos(Exx/Et)
    Extot += Ex
    Eytot += Ey
    Eztot += Ez
    Et=(Extot**2+Eytot**2+Eztot**2)**0.5
Etot = (Extot**2+Eytot**2+Eztot**2)**0.5

print(f'O vetor campo elétrico resultante no ponto A = {Extot: .1E}i + {Eytot: .1E}j + {Eztot: .1E}k')
print(f'O módulo do vetor campo elétrico resultante ={Etot: .1E}.')

O vetor campo elétrico resultante no ponto A = -8.5E+06i + -8.5E+06j + -8.5E+06k
O módulo do vetor campo elétrico resultante = 1.5E+07.
